on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v20
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - name: npm install
      run: npm ci
    - name: build
      uses: npm run build